### ISSUE TITLE
Shiny dashboard for end users

### ISSUE THREAD

**Issue by jhollway** [globalgov/manydata#164]

**Comment by henriquesposito** [comment]
This is a very cool feature that we can even incorporate in our pkgdown websites, if we want to facilitate access through the package website. See https://www.r-bloggers.com/2020/09/embedding-flexdashboard-in-pkgdown-site/

**Comment by BBieri** [comment]
Stumbled upon this neat package that just had its first major release and might be useful in our case. See [{leprechaun}](https://leprechaun.opifex.org/#/).

**Comment by EstherPeev** [comment]
Thanks @henriquesposito and @BBieri. I'll have a look at those features/packages and see how we can use them with our packages.
