### ISSUE TITLE
Update cheatsheet

### ISSUE THREAD

**Issue by jhollway** [globalgov/manydata#167]

**Comment by EstherPeev** [comment]
Here is below the first draft of the cheat sheet for qData. I guess there will be a lot of things to adapt as the functions from qData evolve, but it gives a first overlook of what the final cheat sheet might look like. There are still some space left for future functions or to expand the information on the current functions. 

[https://app.zenhub.com/files/291753904/3f393420-8ca3-4bab-9351-343186f7d800/download](https://app.zenhub.com/files/291753904/3f393420-8ca3-4bab-9351-343186f7d800/download)

Please @henriquesposito, @jhollway let me know if you have some comments or suggestions on the draft.
