### ISSUE TITLE
Make so that resolve argument in `consolidate()` can be specified differently for variables

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/manydata#185]
For example, if user wants to resolve Beg column for "min" date and End column for "max" date...

**Comment by henriquesposito** [comment]
A first working version of this feature has been added. Still needs some more work, but you can now resolve different variables different if you want to!

**Comment by jhollway** [comment]
Fantastic! This is a one-to-one match at the moment? Or can we specify sets of variables a la `starts_with("treaty_")`?

**Comment by henriquesposito** [comment]
For now, yes, it only resolves specified variables in the specified ways (if more than one variable and resolve argument are passed as a list). This was a compromise to keep the structure of the function consistent and intuitive for users (i.e. not add more arguments to the function). As I said, there are still some ties to knot there, specially in regards to how the arguments in the helper functions are setup, how "messydt" objects are resolved, and the addition of a few more resolve methods. I will try and also see if we can resolve for sets of variables, this might be possible with a few alterations to the current function.
