### ISSUE TITLE
Implement package caching into qVerse's GitHub actions

### ISSUE THREAD

**Issue by BBieri** [globalgov/manydata#187]
Review the workflows of all packages currently in the qVerse and standardize them as well as speeding them up with [package caching](https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows).

**Comment by jhollway** [comment]
Is this still a major outstanding issue, @BBieri ? Also came across `[{pak}](https://github.com/r-lib/pak)`, which might be of interest for `get_packages()`?
