### ISSUE TITLE
Improve `consolidate()` function 

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/manydata#191]
Currently consolidate has many more methods implemented, but this has slowed down the function and has made most the variables returned character class...

- To improve the speed and make the function more concise, we should reduce the number of for loops...
- We can resolve variables differently if they are not in character or messydt classes, keeping their original class...
- We were also getting some warnings related to NAs (specifically related to the NA remove argument for resolving dates with messydates), for now we suppress the warnings and sub NAs introduced in the resolve step by the first non NA value (coalesce). There were not many NAs returned when resolving to begin with but double check if this is the best way to proceed.

**Comment by jhollway** [comment]
I can only spot one for loop in the development version of `consolidate()`. Is this really slowing things down a lot? Have we got some profiling data on which parts of the function could/should be refactored?

**Comment by henriquesposito** [comment]
There is one for loop in the main `consolidate()` function, you are right. However, there are two for loops for each helper function called by `consolidate()` to resolve the data. 

The main issue relates to resolving "messydt" class objects for which each element in each column is expanded and then resolved before the columns are resolved into one. This is all done by for loops. I am sure there is a better way of doing this, specially for "messydt" objects. Also, if we have multiple variables to be resolved differently, this will take more time as multiple resolve helper functions are called.

Now that all is working with `consolidate()`, I will work on improving the ways in which it works to make it both faster and more concise(). This is why I opened this issue.

**Comment by henriquesposito** [comment]
I have played around with consolidate these past couple of days and, beside fixing some documentation issues and addressing minor issues with warnings, the function appears to run great!

- The function runs relatively fast and, although I was not able to reduce the number of loops for now (I could not get the function to resolve different variables differently otherwise), it all works well. Also, profiling the function has shown that expanding dates with messydates is what takes the most time not the loops. 

- As it stands, the variables will keep on being returned as character not only due to how they are resolved but also how they are merged/joined in the returned dataset. To keep the class would require a few conversions which might slow down the function. Also, once the variables are returned in a dataset, users can always convert to the class they would like.  

- The issue with NA warnings has been partially resolved, but we keep subbing any NAs returned when resolving conflicts with the first non-missing value when possible.
