### ISSUE TITLE
Allow for key vector in consolidate() instead of single key variable

### ISSUE THREAD

**Issue by BBieri** [globalgov/manydata#202]
`dplyr::inner_join()` and `dplyr::full_join()` allow for a named vector to be passed to the `key` argument. We could implement this feature as well in our `consolidate()` function to allow for an easier joining of panel data for instance where individual observations are identified by a "country-year" pair. Here is an example:

``` r
consolidate(emperors, "any", "every", resolve = "min", key = c("ID" = "ID", "Year" = "Year"))
```

**Comment by jhollway** [comment]
Yes, this would be excellent.

**Comment by jhollway** [comment]
Hi @henriquesposito , indeed lots to consider here.

1. Do the same named keys need to be in every database, or can we allow matching as in dplyr, e.g. `key = c("ID" = "id")`?
2. Yes, every/every would be a pretty demanding expectation
3. When would one resolve a variable that you are using as a key?

**Comment by henriquesposito** [comment]
I apologise for the mistake, yes, one should not resolve a variable that you are using as a key. The function indeed works for resolving multiple variables differently if we have multiple keys, for example:

`consolidate(database = emperors, rows = "any", cols = "any",
resolve = c(Death = "max", Cause = "coalesce"),
key = c("ID", "Beg"))`

Ideally the same named keys should to be in every database for consolidate(), however, matching is possible if equivalent key columns across datasets have a different name. Say for instance that the id column in the wikipedia dataset for the emperors database is named "id" and the id column in the other datasets are named "ID", in that case we can indeed use key = c("ID" = "id") to declare that these keys are the same. For example:
`library(manydata)
w <- emperors$wikipedia
u <- emperors$UNRV
b <- emperors$britannica
w <- dplyr::rename(w, id = "ID")
e <- tibble::lst(w, u, b)
consolidate(e, "any", "any", "coalesce", key = c("id" = "ID"))`

I will update the function documentation to include a description for multiple keys and matching of differently named key variables.
