### ISSUE TITLE
Update network_map() function

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/manydata#222]
Function requires some packages not imported in manydata and, more importantly, it relies on a function in manystates to download cshape files... 

@jaeltan could you please make sure this is a feasible function to add to manydata considering CRAN requirements? If it is, we need to add the necessary package dependencies, update documentation, and helper functions.

**Comment by jaeltan** [comment]
The function now uses the `cshp()` function in `{cshapes}` package (instead of the `import_cshapes()` function in `{manystates}`) to download the data on latitude and longitude.

**Comment by henriquesposito** [comment]
Thank you for all the great work adding the function to manydata @jaeltan ! I have two further suggestions here. First, could we adapt (or change) the current example so that it runs without generating notes/warnings? Second, could we somehow substitute the `{countrycode}` dependency? We only use the function to code names so perhaps we can use one of our house solutions by moving one of the "sysfiles" we already have to manydata. Thank you!

**Comment by jhollway** [comment]
Yes, we should use the in-house manystates (or is it in manypkgs now?) sysdata

**Comment by jaeltan** [comment]
Countryregex has been added to sysdata in `manydata` and countrycode dependency has been removed
