### ISSUE TITLE
Make `coalesce_compatible()` faster

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/manydata#228]
For now, some consolidations in manyenviron take over 30 minutes and this is related to how we identify and coalesce duplicate rows. 

Using duplicated (with from last) is rather slow (see https://stackoverflow.com/questions/37148567/fastest-way-to-remove-all-duplicates-in-r) so perhaps we can speed things up using rle and sort (see https://stackoverflow.com/questions/1923273/counting-the-number-of-elements-with-the-values-of-x-in-a-vector).

**Comment by jhollway** [comment]
Would it help accelerate the `manyenviron::memberships` consolidation to outsource the identification of distinct agreements to a first consolidation of `manyenviron::agreements`?
