### ISSUE TITLE
Set up manyigos

### ISSUE THREAD

**Issue by jaeltan** [globalgov/manydata#239]

**Comment by jaeltan** [comment]
Datasets to add:
1. COW IGO v3 dataset
2. IIGO dataset (Vabulas and Snidal)
3. Death of IGOs dataset (Eilstrup-Sangiovanni)
4. Vitality of IGOs dataset (Gray)

**Comment by jhollway** [comment]
A(n empty) repository is set up [here](https://github.com/globalgov/manyigos/). @jaeltan, can you please create a new manypkg there with the various IGOs datasets?

Also, how feasible would it be to add e.g. International Associations Yearbook of International Organisations?

**Comment by jaeltan** [comment]
I wasn't able to scrape the publicly available table on the website, we might need to get access to add the Yearbook

**Comment by jaeltan** [comment]
@jhollway there is already a scraped YIO dataset in manyenviron, but I think it would make more sense to move that and the MIA dataset into manyigos instead, what do you think?

**Comment by jhollway** [comment]
Sure, sounds good
