### ISSUE TITLE
Need to install (update) multiple packages at once

### ISSUE THREAD

**Issue by jhollway** [globalgov/manydata#251]
To save time, need to be able to pass `get_packages()` a vector of package names, numbers from the table, or choose (as an argument or another function) `update_all` to update all those packages that have an installed version number behind the latest available version number.

**Comment by henriquesposito** [comment]
A first working version of this feature, as an argument, has been added. I will re-work how it works to make it faster and more concise.

**Comment by henriquesposito** [comment]
Update and setup this option as a look up
