### ISSUE TITLE
Create a heatmap (plot) for dataset comparisons within database

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/manydata#257]
The rows are the unique observations, the columns are the datasets, and the cells' color/saturation/opacity is a function of how many non-missing cells there are for that observation in that dataset.

**Comment by jhollway** [comment]
I really like it @henriquesposito. Maybe we can go green to red to get a little more contrast with the white background? (Or perhaps a more colour-blind friendly pairing?) Also, I wondered if there is a reason why the databases are on the x-axis and the variables on the y-axis? And then what is the logic for the ordering of the variables?

**Comment by henriquesposito** [comment]
This has become `compare_missing()` (see issue #261).
