### ISSUE TITLE
Revise CCC structure for manydata

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/manydata#259]
The collect, correct, and connect (CCC) structure of manydata is not appropriate anymore. This is reflective of a time when manydata and manypkgs were one package.

One alternative is to frame the PANARCHIC project, as a whole, in regards to a CCC structure. The "collect" portion could relate to the data packages, the correct/code portion could be reflective of manypkgs, and the connect/consolidate portion could relate to manydata.

In any case, the cheatsheet for manydata should change...

**Comment by jhollway** [comment]
It seems collect, correct, connect applies mostly to manypkgs. Why not find a different structure for the manydata cheatsheet? E.g. More specifically on how `get_packages()` and `consolidate()` work

**Comment by henriquesposito** [comment]
Thank you @jaeltan , the AAA structure sound great!

In case we want to keep the CCC initials, we could also go with Compile/Compare/Consolidate.

**Comment by jhollway** [comment]
I really like @jaeltan's AAA motto: Access is great, maybe Amalgamate instead of Assemble (since it is not disassembled), and maybe Analyze/Analyse for the others? Or, indeed if also Cs, then Call, Consolidate, Compare?

**Comment by jaeltan** [comment]
I think if we want to keep it simple Call/Compare/Consolidate works better than the AAA

**Comment by jhollway** [comment]
Alternative Cs could be Catch or Capture.

@jaeltan , your 'Call'.

**Comment by jaeltan** [comment]
I stuck to Call/Consolidate/Compare, please see attached for the updated cheatsheet. @jhollway @henriquesposito please let me know if you have any comments and suggestions, thank you!
[https://app.zenhub.com/files/291753904/f413f6c9-29a3-434b-953f-3050c5ffd447/download](https://app.zenhub.com/files/291753904/f413f6c9-29a3-434b-953f-3050c5ffd447/download)

**Comment by henriquesposito** [comment]
Thank you so much @jaeltan for the work! The structure makes much more sense now indeed.

Could we perhaps try one with the AAA structure you proposed? I wonder if the CCCs will cause confusion between `{manydata}` and `{manypkgs}`. In turn, this CCC overlap might be wanted...

**Comment by henriquesposito** [comment]
Thank you very much @jaeltan ! I actually really like the AAA structure as well, though I am not sure if "amalgamate" is the right word to describe database consolidation.

**Comment by jhollway** [comment]
Doesn't need to be alliteration. Could be get, consolidate, and analyse or compare. I think the visual for `get` could be revisited though.

**Comment by jaeltan** [comment]
I've updated the visual for `get_packages()`, please let me know if you have any suggestions/comments. I've kept the CCC alliteration for now because I think the alliteration makes it more memorable, but Access or Get also works with Consolidate and Compare.

[https://app.zenhub.com/files/291753904/efe20f09-abad-4b57-b92a-38fa239d895a/download](https://app.zenhub.com/files/291753904/efe20f09-abad-4b57-b92a-38fa239d895a/download)
