### ISSUE TITLE
Create a get or a call source function

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/manydata#269]
For `get_source()`:

- Add description column about each dataset 
- Add URL for HUGGO and AIGGO (maybe panarchic.ch) - also can we make it clickable see issue #267
- Maybe add a separate codebook variable for codebook, since we are removing `open_codebook()`
- Create a new variable called "Variable mapping" for the columns that have changed names and how, since we are removing `data_evolution()` (this might require we save an internal data file with this info that we can quickly get it without going through GitHub)

**Comment by henriquesposito** [comment]
I have added this function but, as it is currently setup, it would require we complete the databases/datasets in other many packages. I taught about this a great deal and I think using the database help file to both get details of the data is great way around downloading data from GitHub (and running into API limits) as well as making our database help files more complete and transparent. @jaeltan please let me know what you think about this solution. Thank you.

**Comment by jaeltan** [comment]
I agree the (reformatted) help files would be a good source of getting the information. At first glance I wasn't sure what the values in the 'mapping' column were supposed to be, could we have two separate columns instead? One column listing the original variable names (where applicable) and another column for the new variable names?
