### ISSUE TITLE
Bug with `compare_dimensions()` 

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/manydata#295]
The following works when running within `{manydata}`but not elsewhere. I am not sure why but it seems to be related to how `{messydates}` processes NAs after the latest changes.

```r
manydata::compare_dimensions(manyenviron::agreements)
```

**Comment by henriquesposito** [comment]
This appears to have been fixed with the latest changes in `{messydates}` that update how the package deals with NAs.

**Comment by jhollway** [comment]
If this isn't actually awaiting deployment, you can just close the issue?
